version: '3'

services:
  db:
    image: mysql:8
#    container_name: mysql8-01
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: hello
      MYSQL_USER: user01
      MYSQL_PASSWORD: 123456
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./config:/etc/mysql/conf.d/my.cnf
    - ./initdb:/docker-entrypoint-initdb.d
    - ./data:/var/lib/mysql
    ports:
    - 33062:3306
