version: '3'

services:
  hello-mysql-db-dev:
    image: mysql:8
    container_name: hello-mysql-db-dev
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: hello
      MYSQL_USER: user01
      MYSQL_PASSWORD: 123456
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./config:/etc/mysql/conf.d/my.cnf
    - ./initdb:/docker-entrypoint-initdb.d
    - ./data:/var/lib/mysql
    ports:
    - 33061:3306

  hello-mysql-gui-dev:
    container_name: hello-mysql-gui-dev
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=hello-mysql-db-dev
    - PMA_USER=root
    - PMA_PASSWORD=12345678
    ports:
    - 33051:80
    depends_on:
      - hello-mysql-db-dev

networks:
  default:
    name: hello-network-dev
